### ISSUE TITLE
Brew's formula is disabled

### ISSUE THREAD

**Issue by aisamu** [owickstrom/komposition#105]
Following the installation instructions for `brew` fails with: 

```sh
❯ brew install komposition         
Error: komposition has been disabled because it does not build!
```

The formula indeed shows up as disabled on brew.sh:
*  https://formulae.brew.sh/formula/komposition

**Desktop**
 - OS: macOS 11.1
 - Build environment: `brew`

**Additional context**
I've also tried installing it via `nix`, but it unfortunately didn't work as well! 
Happy to provide more information on a separate ticket!

Looking forwards to trying Komposition.
Thanks for writing it!

**Comment by owickstrom** [comment]
Hmm, I'm not sure what's going on here with Homebrew. @athas would like to have a look?

Regarding Nix, that might be a macOS problem. I've tried it on Linux and it worked, except for some problem with the fonts. Can you provide some logs?

**Comment by athas** [comment]
There is/was a fix to the macOS issue in #101, but the PR never got merged because CI is stuck, and there is a hard restriction on merging anything without positive CI results.

**Comment by owickstrom** [comment]
Ouch. I'll see if I can get it past CI in the coming days.

**Comment by owickstrom** [comment]
This turned out to be a lot more painful than I had hoped for. `fused-effects` has changed quite a lot since I worked on this (it was then 0.1.x). I'm suspecting changes to `massiv` might cause breakage too. Alternative is to stay on the old versions but then we're also stuck with an old nixpkgs revision. 

To be honest, I don't have to energy or time to fix these things and maintain the project, esp. as I'm no longer making screencasts. If anyone would like to take it over and keep it up date, let me know. If not, maybe I should "archive" this repository.

**Comment by owickstrom** [comment]
@athas do you have any ideas here? It seems this codebase is suffering from severe bit rot, and I have basically zero time or energy to work on it nowadays. The `fused-effects` stuff is quite pervasive, too, so it's a _big_ task to remove it or rewrite it for their new APIs.

If there's no new maintainer keen on doing the work, I suggest we archive the repository.

**Comment by athas** [comment]
I don't think I have the stomach for working with effect systems in Haskell.

**Comment by owickstrom** [comment]
> I don't think I have the stomach for working with effect systems in Haskell.

😆 I hear you. 

I'll archive it now. If someone wants to revive this project then go ahead and fork.
